name: 'audit_helper_ext'
require-dbt-version: [">=1.7.0", "<2.0.0"]

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  audit_helper_ext:
    +database: "{{ var('audit_helper__database', target.database) }}"
    +schema: "{{ var('audit_helper__schema', target.schema) }}"

vars:
  # audit_helper__database: audit_helper_ext
  # audit_helper__schema: validation
