name: audit_helper_ext
require-dbt-version: [">=1.7.0", "<2.0.0"]

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

vars:
  # audit_helper__dbt_cloud_host_url: cloud.getdbt.com
  # audit_helper__database: audit_helper
  # audit_helper__schema: log
  # audit_helper__date_of_process: 2024-09-09 # default to UTC now if not specified
  # audit_helper__allowed_date_of_processes: ['2024-09-09', '2024-09-10']
  # audit_helper__source_database: ???
  # audit_helper__source_schema: ???
  # audit_helper__old_identifier_naming_convention:
  #   pattern: '^(.*)$'
  #   replacement: 'dim_\1' # dbt=customers vs old=dim_customers
  # audit_helper__print_table_enabled: yes
  # audit_helper__audit_query_pre_hooks: [] # list of SQL queries to execute before each audit query
  # audit_helper__audit_query_pre_hooks: # PostgreSQL: disable parallel execution to improve match rate
  #   - 'SET max_parallel_workers_per_gather = 0'
  # audit_helper__audit_query_statement_separator: ';' # statement separator for pre-hooks (use 'GO' for SQL Server)
  # audit_helper__validation_result_filters: # used for reporting in-terminal
  #   - name: count__mismatch
  #     description: Row counts do not match between A and B
  #     macro: filter_count_validation_mismatch
  #     validation_type: count
  #     failed_calc:
  #       column: TOTAL_RECORDS
  #   - name: full__in_a_not_b
  #     description: Rows exist in A but missing in B
  #     macro: filter_full_validation_in_a_not_b
  #     validation_type: full
  #     failed_calc:
  #       agg: sum
  #       column: COUNT
