name: audit_helper_ext
require-dbt-version: [">=1.7.0", "<2.0.0"]

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

vars:
  # audit_helper__dbt_cloud_host_url: emea.dbt.com
  # audit_helper__database: audit_helper
  # audit_helper__schema: log
  # audit_helper__date_of_process: 2024-09-09 # default to UTC now if not specified
