name: 'audit_helper_ext_test'
version: '0.0.0'
config-version: 2

profile: 'audit_helper_ext'

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

dbt-cloud: # for dbt Cloud CLI
  project-id: 380261
  account-host: cloud.getdbt.com

on-run-start:
  - > # create target.schema if not exists
    create schema if not exists {{ target.schema }}

on-run-end:
  - > # clone from `audit_helper_ext_seed` to `audit_helper_ext_seed__20240912`
    {% if flags.WHICH in ["seed", "build"] %}
      {{ audit_helper_ext.clone_schema(source_schema="audit_helper_ext_seed") }}
    {% endif %}

seeds:
  audit_helper_ext_test:
    +schema: audit_helper_ext_seed # Target Day 1 -- will be cloned to `audit_helper_ext_seed__20240912`
    sample:
      sample_target_1:
        +alias: sample_1
      sample_target_2:
        +schema: audit_helper_ext_seed__20240913 # Target Day 2
        +alias: sample_1

vars:
  audit_helper__allowed_date_of_processes: ['2024-09-12', '2024-09-13']
  audit_helper__date_of_process: "2024-09-12"
  audit_helper__source_schema: audit_helper_ext_seed
  audit_helper__old_identifier_naming_convention:
    pattern: '^(.*)$'
    replacement: 'raw_\1' # prefix raw_
