name: 'audit_helper_ext_test'
version: '0.0.0'
config-version: 2

profile: 'audit_helper_ext'

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

on-run-end:
  - > # freeze the source with __YYYYMMDD version = audit_helper_ext_seed__YYYYMMDD
    {% if flags.WHICH in ["seed", "build"] %}
      {{ audit_helper_ext.clone_schema(source_schema="audit_helper_ext_seed") }}
    {% endif %}

seeds:
  audit_helper_ext_test:
    +schema: audit_helper_ext_seed
    sample:
      sample_source_1:
        +alias: sample_1
    jaffle_shop:
      raw_customers:
        +alias: customers
      raw_items:
        +alias: items
      raw_orders:
        +alias: orders
      raw_products:
        +alias: products
      raw_stores:
        +alias: stores
      raw_supplies:
        +alias: supplies

vars:
  audit_helper__schema: log
  audit_helper__date_of_process: "2024-09-12"
  audit_helper__source_schema: audit_helper_ext_seed
