audit_helper_ext:
  target: mssql
  outputs:
    mssql:
      type: sqlserver
      driver: ODBC Driver 18 for SQL Server
      port: 1433
      server: 127.0.0.1
      database: audit_helper_ext
      schema: dbo
      authentication: sql
      user: dbt_user
      password: "YourStrong@Passw0rd" # CAUTIOUS: this is for testing only
      trust_cert: true